### ISSUE TITLE
[暂定]2017-08-30 王滨老师家里自主研发晚餐购物清单

### ISSUE THREAD

**Issue by wujun4code** [wujun4code/what-to-eat#1]
### 副食品
- [x] 生抽
- [x] 老抽
- [x] 黄酒或者料酒
- [ ] 芝麻油
- [ ] 八角(俗称大料)
- [ ] 桂皮
- [ ] 干辣椒
- [x] 大蒜子
- [x] 生姜
- [x] 新鲜小葱一把

### 厨具和餐具
- [x] 电压力锅 x 1
- [x] 炒锅 x 1
- [ ] 菜盘 x 4
- [x] 大汤碗 x 1

**Comment by wujun4code** [comment]
## 红烧鸡翅中
预览图：
![image](https://user-images.githubusercontent.com/5119542/29769547-6aa98056-8c1d-11e7-8bec-0b40478e41c2.png)

下厨房连接 - [经典红烧鸡翅中](https://www.xiachufang.com/recipe/37778/) 

## 所需材料
- [x] 鸡翅中 2 只/人
- [x] 冰糖

**Comment by wujun4code** [comment]
## 红烧冬瓜
下厨房连接:[红烧冬瓜](https://www.xiachufang.com/recipe/23410/)
截图：
![image](https://user-images.githubusercontent.com/5119542/29770005-66784128-8c1f-11e7-9bb4-af4ad51aca67.png)

## 所需材料
- [ ] 冬瓜
- [x] 蚝油 
- [x] 鸡精

**Comment by wujun4code** [comment]
## ~~红烧排骨~~
下厨房连接：[红烧排骨](https://www.xiachufang.com/recipe/9730/)
截图：
![image](https://user-images.githubusercontent.com/5119542/29770107-fc487010-8c1f-11e7-9c32-1c137b97cb7d.png)

- [x] 排骨 100克/人

**因为压力锅未到，这道菜在没有压力锅的情况下需要耗时超过 80 分钟，遂弃之**

**Comment by feisuzhu** [comment]
给推荐个压力锅

**Comment by feisuzhu** [comment]
我没法编辑

**Comment by wujun4code** [comment]
## 葱炒蛤蜊
下厨房连接：[葱炒蛤蜊](https://www.xiachufang.com/recipe/100302775/)
![image](https://user-images.githubusercontent.com/5119542/29770208-6ebab1f8-8c20-11e7-8feb-00d50df1fe73.png)

## 所需材料
- [x] 黑胡椒粉 
- [x] 花蛤 100g/人

**Comment by wujun4code** [comment]
## [家常烧腐竹](https://www.xiachufang.com/recipe/100583987/)
![image](https://user-images.githubusercontent.com/5119542/29770417-90390a7c-8c21-11e7-9833-c17e035c1c55.png)

- [x] 腐竹 100g/人

**Comment by wujun4code** [comment]
## 生炒五花肉 
![image](https://user-images.githubusercontent.com/5119542/29853802-93733c7c-8d74-11e7-998d-52b0839b56c8.png)


- [ ] 豆瓣酱 | 15克
- [ ] 五花肉 | 50克/人
- [ ] 青蒜苗 | 200克
